### ISSUE TITLE
ERROR: LICENSE was not found in the build directory and is not a URL. 

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [shuye02/AUR-sendanywhere#1]
```
==> ERROR: LICENSE was not found in the build directory and is not a URL.
```

**Comment by shuye02** [comment]
The license file is located in the same directory as the PKGBUILD (if you have cloned this entire repo it would be fine)

According to the [Arch Wiki](https://wiki.archlinux.org/index.php/PKGBUILD#source), this should work with no problem

**Comment by ZhengshuaiPENG** [comment]
So your PKGBUILD only can be installed in local.

What I have done is use yaourt to install the sendAnyWhere, and just change the PKGBUILD as yours, it will report this error. 

I wonder if you can take over the AUR sendanywhere repo to make it work?

**Comment by shuye02** [comment]
Instead of using yaourt, you may clone this repo and run `makepkg -si` to install the package.

If you want to stick with the current AUR package, you need to **add the `LICENSE` file** to the source folder as well as the `PKGBUILD`.

For the last question, I'm trying to. I've already submitted an orphan request on AUR and I've got no response.

Perhaps you could try submitting another orphan request so someone would approve it.

**Comment by shuye02** [comment]
FYI, I've added the official LICENSE to the PKGBUILD, that's why yaourt fails.

Because there is **NO** LICENSE file in the original AUR package (which is disrespectful to the legal rights of the company), yaourt cannot found that LICENSE file, thus resulting in the source not found error.

**Comment by shuye02** [comment]
@ZhengshuaiPENG I have adopted the package as a maintainer on AUR now, you can now install it from AUR.
Closing this issue now
